version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mealplan-db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  mealplanapi:
    build:
      context: .                      
      dockerfile: MealPlanApp/Dockerfile
    container_name: mealplan-api
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MealPlanDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    restart: always
